services:
  # https://github.com/haugene/docker-transmission-openvpn
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    ports:
      - "0.0.0.0:9091:9091"
    # https://haugene.github.io/docker-transmission-openvpn/config-options/
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_COUNTRY=ES
      - OPENVPN_CATEGORY=legacy_p2p
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_WEB_UI=flood-for-transmission
    volumes:
      - /media/downloads:/data
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN

  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "0.0.0.0:7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ~/media-server-config/radarr:/config
      - /media/movies:/movies
      - /media/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "0.0.0.0:8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ~/media-server-config/sonarr:/config
      - /media/tv:/tv
      - /media/downloads/completed:/downloads


  # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    ports:
      - "0.0.0.0:9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ~/media-server-config/prowlarr:/config
      - /media/downloads/watch:/downloads

  # https://github.com/dperson/samba
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: always
    # NOTE: see https://github.com/dperson/samba#troubleshooting
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "139:139"
      - "445:445"
    environment:
      - USERID=1000
      - GROUPID=1000
      - SHARE=Media;/media
      - TZ=Europe/Amsterdam
    volumes:
      - /media:/media

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}     # https://account.plex.tv/en/claim
    volumes:
      - ~/media-server-config/plex:/config
      - /media:/media    
    restart: unless-stopped

