networks:
  media-network:
    driver: bridge

services:
  # https://github.com/haugene/docker-transmission-openvpn
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    ports:
      - '9091:9091'
    # https://haugene.github.io/docker-transmission-openvpn/config-options/
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_COUNTRY=ES
      - OPENVPN_CATEGORY=legacy_p2p
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TRANSMISSION_DOWNLOAD_DIR=/data/downloads/completed
      - TRANSMISSION_INCOMPLETE_DIR=/data/downloads/incomplete
      - TRANSMISSION_WATCH_DIR=/data/downloads/watch
    volumes:
      - /mnt/media-drive/media:/data
      - /mnt/media-drive/media-server-config/transmission:/config
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    networks:
      - media-network

  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - '7878:7878'
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media-drive/media-server-config/radarr:/config
      - /mnt/media-drive/media:/data
    networks:
      - media-network

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - '8989:8989'
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media-drive/media-server-config/sonarr:/config
      - /mnt/media-drive/media:/data
    networks:
      - media-network

  # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    ports:
      - '9696:9696'
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media-drive/media-server-config/prowlarr:/config
      - /mnt/media-drive/media:/data
    networks:
      - media-network

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM} # https://account.plex.tv/en/claim
    volumes:
      - /mnt/media-drive/media-server-config/plex:/config
      - /mnt/media-drive/media:/media
    restart: unless-stopped
